//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BecquerelMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BecquerelMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BecqMoni2011.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose background spectrum file.
        /// </summary>
        internal static string BackgroundSelectionDialogTitle {
            get {
                return ResourceManager.GetString("BackgroundSelectionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bar {
            get {
                object obj = ResourceManager.GetObject("bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon becqmoni {
            get {
                object obj = ResourceManager.GetObject("becqmoni", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BecqMoniLogo {
            get {
                object obj = ResourceManager.GetObject("BecqMoniLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (Beta program expires at {0}).
        /// </summary>
        internal static string BetaProgramExpirationDateString {
            get {
                return ResourceManager.GetString("BetaProgramExpirationDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BG {
            get {
                object obj = ResourceManager.GetObject("BG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bgfit {
            get {
                object obj = ResourceManager.GetObject("bgfit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap channel {
            get {
                object obj = ResourceManager.GetObject("channel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Background Counts:.
        /// </summary>
        internal static string ChartHeaderBGCounts {
            get {
                return ResourceManager.GetString("ChartHeaderBGCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Channel:.
        /// </summary>
        internal static string ChartHeaderChannel {
            get {
                return ResourceManager.GetString("ChartHeaderChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BG Ratio:.
        /// </summary>
        internal static string ChartHeaderCountBGRatio {
            get {
                return ResourceManager.GetString("ChartHeaderCountBGRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Energy[keV]:.
        /// </summary>
        internal static string ChartHeaderEnergy {
            get {
                return ResourceManager.GetString("ChartHeaderEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FWHM:.
        /// </summary>
        internal static string ChartHeaderFWHM {
            get {
                return ResourceManager.GetString("ChartHeaderFWHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gross Counts:.
        /// </summary>
        internal static string ChartHeaderGrossCounts {
            get {
                return ResourceManager.GetString("ChartHeaderGrossCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Net Counts:.
        /// </summary>
        internal static string ChartHeaderNetCounts {
            get {
                return ResourceManager.GetString("ChartHeaderNetCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Net CPS:.
        /// </summary>
        internal static string ChartHeaderNetCps {
            get {
                return ResourceManager.GetString("ChartHeaderNetCps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected Region.
        /// </summary>
        internal static string ChartHeaderSelection {
            get {
                return ResourceManager.GetString("ChartHeaderSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cnt {
            get {
                object obj = ResourceManager.GetObject("cnt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation.
        /// </summary>
        internal static string ConfirmationDialogTitle {
            get {
                return ResourceManager.GetString("ConfirmationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  (Copy).
        /// </summary>
        internal static string CopyPostfix {
            get {
                return ResourceManager.GetString("CopyPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cps {
            get {
                object obj = ResourceManager.GetObject("cps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cps1 {
            get {
                object obj = ResourceManager.GetObject("cps1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cps2 {
            get {
                object obj = ResourceManager.GetObject("cps2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export to CSV File.
        /// </summary>
        internal static string CsvExportDialogTitle {
            get {
                return ResourceManager.GetString("CsvExportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CSV Files (*.csv)|*.csv|All Files (*.*)|*.*.
        /// </summary>
        internal static string CsvFileFilter {
            get {
                return ResourceManager.GetString("CsvFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import from CSV File.
        /// </summary>
        internal static string CsvImportDialogTitle {
            get {
                return ResourceManager.GetString("CsvImportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete spectrum &quot;{0}&quot;?.
        /// </summary>
        internal static string DeleteSpectrumMessage {
            get {
                return ResourceManager.GetString("DeleteSpectrumMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete unnamed spectrum?.
        /// </summary>
        internal static string DeleteUnnamedSpectrumMessage {
            get {
                return ResourceManager.GetString("DeleteUnnamedSpectrumMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AtomSpectraVCP.
        /// </summary>
        internal static string DeviceTypeAtomSpectraVCP {
            get {
                return ResourceManager.GetString("DeviceTypeAtomSpectraVCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audio Input Device.
        /// </summary>
        internal static string DeviceTypeAudioInput {
            get {
                return ResourceManager.GetString("DeviceTypeAudioInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LEMCA USB Adaptor.
        /// </summary>
        internal static string DeviceTypeLEMCA {
            get {
                return ResourceManager.GetString("DeviceTypeLEMCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ene {
            get {
                object obj = ResourceManager.GetObject("ene", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EnergyCalibration {
            get {
                object obj = ResourceManager.GetObject("EnergyCalibration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EnergyCalibration2 {
            get {
                object obj = ResourceManager.GetObject("EnergyCalibration2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specified file is already open..
        /// </summary>
        internal static string ERRAlreadyOpen {
            get {
                return ResourceManager.GetString("ERRAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specified audio device is not found..
        /// </summary>
        internal static string ERRAudioDeviceNotFound {
            get {
                return ResourceManager.GetString("ERRAudioDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to load background spectrum &quot;{0}&quot;..
        /// </summary>
        internal static string ERRBackgroundLoadFailure {
            get {
                return ResourceManager.GetString("ERRBackgroundLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to connect device. Check cable connection and power of the device..
        /// </summary>
        internal static string ERRCannotConnectDevice {
            get {
                return ResourceManager.GetString("ERRCannotConnectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t delete spectrum. at least one spectrum per file is needed..
        /// </summary>
        internal static string ERRCannotDeleteSpectrum {
            get {
                return ResourceManager.GetString("ERRCannotDeleteSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t open WAV file..
        /// </summary>
        internal static string ERRCannotOpenWavFile {
            get {
                return ResourceManager.GetString("ERRCannotOpenWavFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t overwrite any opened file.
        /// </summary>
        internal static string ERRCannotOverwrite {
            get {
                return ResourceManager.GetString("ERRCannotOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to retreive device data. (prohibited while measurement processing)
        ///.
        /// </summary>
        internal static string ERRCannotRetreiveDeviceData {
            get {
                return ResourceManager.GetString("ERRCannotRetreiveDeviceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error detected while communicating with device.
        ///.
        /// </summary>
        internal static string ERRDetectedErrorWhileCommunication {
            get {
                return ResourceManager.GetString("ERRDetectedErrorWhileCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Device configuration is not selected..
        /// </summary>
        internal static string ERRDeviceConfigNotSelected {
            get {
                return ResourceManager.GetString("ERRDeviceConfigNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duplicate or invalid configuration name..
        /// </summary>
        internal static string ERRDuplicateConfigName {
            get {
                return ResourceManager.GetString("ERRDuplicateConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duplicate GUID for deivce configuration &quot;{0}&quot;.
        /// </summary>
        internal static string ERRDuplicateDeviceConfigGUID {
            get {
                return ResourceManager.GetString("ERRDuplicateDeviceConfigGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duplicate GUID for ROI configuration &quot;{0}&quot;.
        /// </summary>
        internal static string ERRDuplicateROIConfigGUID {
            get {
                return ResourceManager.GetString("ERRDuplicateROIConfigGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excel may not be installed.
        /// </summary>
        internal static string ERRExcelNotInstalled {
            get {
                return ResourceManager.GetString("ERRExcelNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File &quot;{0}&quot; couldn&apos;t be opened.
        ///({1}).
        /// </summary>
        internal static string ERRFileOpenFailure {
            get {
                return ResourceManager.GetString("ERRFileOpenFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File &quot;{0}&quot; couldn&apos;t be saved.
        ///({1}).
        /// </summary>
        internal static string ERRFileSaveFailure {
            get {
                return ResourceManager.GetString("ERRFileSaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The firmware must be updated to the latest version..
        /// </summary>
        internal static string ERRFirmwareMustBeUpdated {
            get {
                return ResourceManager.GetString("ERRFirmwareMustBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incompatible channel parameters..
        /// </summary>
        internal static string ERRIncompatibleChannelParameters {
            get {
                return ResourceManager.GetString("ERRIncompatibleChannelParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input device is not set..
        /// </summary>
        internal static string ERRInputDeviceNotSet {
            get {
                return ResourceManager.GetString("ERRInputDeviceNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input an integer..
        /// </summary>
        internal static string ERRInputInteger {
            get {
                return ResourceManager.GetString("ERRInputInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input a number..
        /// </summary>
        internal static string ERRInputNumber {
            get {
                return ResourceManager.GetString("ERRInputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid channel or energy values.
        /// </summary>
        internal static string ERRInvalidChannelOrEnergyValues {
            get {
                return ResourceManager.GetString("ERRInvalidChannelOrEnergyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid device type.
        /// </summary>
        internal static string ERRInvalidDeviceType {
            get {
                return ResourceManager.GetString("ERRInvalidDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid input form..
        /// </summary>
        internal static string ERRInvalidInputForm {
            get {
                return ResourceManager.GetString("ERRInvalidInputForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid preset time..
        /// </summary>
        internal static string ERRInvalidPresetTime {
            get {
                return ResourceManager.GetString("ERRInvalidPresetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid ROI primitive..
        /// </summary>
        internal static string ERRInvalidROIPrimitive {
            get {
                return ResourceManager.GetString("ERRInvalidROIPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid ROI primitive operation..
        /// </summary>
        internal static string ERRInvalidROIPrimitiveOperation {
            get {
                return ResourceManager.GetString("ERRInvalidROIPrimitiveOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to load device configuration file(s)..
        /// </summary>
        internal static string ERRLoadingDeviceConfigFailed {
            get {
                return ResourceManager.GetString("ERRLoadingDeviceConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to load application configuration file..
        /// </summary>
        internal static string ERRLoadingGlobalConfigFailed {
            get {
                return ResourceManager.GetString("ERRLoadingGlobalConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to load nuclide definition file..
        /// </summary>
        internal static string ERRLoadingNuclideDefinitionFile {
            get {
                return ResourceManager.GetString("ERRLoadingNuclideDefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to load ROI configuration file(s)..
        /// </summary>
        internal static string ERRLoadingROIConfigFailed {
            get {
                return ResourceManager.GetString("ERRLoadingROIConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specified WAV format is not supported by the audio device..
        /// </summary>
        internal static string ERRNotSupportedWavFormat {
            get {
                return ResourceManager.GetString("ERRNotSupportedWavFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to save device configuration file..
        /// </summary>
        internal static string ERRSavingDeviceConfigFailed {
            get {
                return ResourceManager.GetString("ERRSavingDeviceConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to save application configuration file..
        /// </summary>
        internal static string ERRSavingGlobalConfigFailed {
            get {
                return ResourceManager.GetString("ERRSavingGlobalConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to save nuclide definition file..
        /// </summary>
        internal static string ERRSavingNuclideDefinitionFile {
            get {
                return ResourceManager.GetString("ERRSavingNuclideDefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to save ROI configuration file..
        /// </summary>
        internal static string ERRSavingROIConfigFailed {
            get {
                return ResourceManager.GetString("ERRSavingROIConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export Selected Spectra To File.
        /// </summary>
        internal static string ExportSpectraToFileDialogTitle {
            get {
                return ResourceManager.GetString("ExportSpectraToFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fit1 {
            get {
                object obj = ResourceManager.GetObject("fit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fit2 {
            get {
                object obj = ResourceManager.GetObject("fit2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HD {
            get {
                object obj = ResourceManager.GetObject("HD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HD1 {
            get {
                object obj = ResourceManager.GetObject("HD1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon256 {
            get {
                object obj = ResourceManager.GetObject("icon256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import Old Format (0.93Beta or earlier) Spectrum File.
        /// </summary>
        internal static string ImportOldFormatFileDialogTitle {
            get {
                return ResourceManager.GetString("ImportOldFormatFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import Spectra From File.
        /// </summary>
        internal static string ImportSpectraFromFileDialogTitle {
            get {
                return ResourceManager.GetString("ImportSpectraFromFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initializing...
        ///.
        /// </summary>
        internal static string InitializingMessage {
            get {
                return ResourceManager.GetString("InitializingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid Input Value.
        /// </summary>
        internal static string InvalidValueDialogTitle {
            get {
                return ResourceManager.GetString("InvalidValueDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на based on pulse shape discrimination algorithm of PRA for audio input devices
        ///http://www.physics.usyd.edu.au/~marek/pra/index.html
        ///
        ///using DockPanel Suite library
        ///http://sourceforge.net/projects/dockpanelsuite/
        ///
        ///using WinMM.Net library
        ///http://winmm.codeplex.com/
        ///
        ///using XPTable library
        ///http://xptable.sourceforge.net/.
        /// </summary>
        internal static string LibraryLicensesMessage {
            get {
                return ResourceManager.GetString("LibraryLicensesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap line {
            get {
                object obj = ResourceManager.GetObject("line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linear {
            get {
                object obj = ResourceManager.GetObject("linear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading File ( {0} )....
        /// </summary>
        internal static string LoadingFileMessage {
            get {
                return ResourceManager.GetString("LoadingFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap log {
            get {
                object obj = ResourceManager.GetObject("log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove device configuration &quot;{0}&quot;?.
        /// </summary>
        internal static string MessageRemoveDeviceConfig {
            get {
                return ResourceManager.GetString("MessageRemoveDeviceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minus {
            get {
                object obj = ResourceManager.GetObject("Minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Energy calibration is done..
        /// </summary>
        internal static string MSGCalibrationDone {
            get {
                return ResourceManager.GetString("MSGCalibrationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear spectrum?.
        /// </summary>
        internal static string MSGClearSpectrum {
            get {
                return ResourceManager.GetString("MSGClearSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuration has been modified. Save?.
        /// </summary>
        internal static string MSGConfirmSaveConfig {
            get {
                return ResourceManager.GetString("MSGConfirmSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete nuclide definition &quot;{0}&quot;?.
        /// </summary>
        internal static string MSGDeleteNuclideDefinition {
            get {
                return ResourceManager.GetString("MSGDeleteNuclideDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove ROI configuration &quot;{0}&quot;?.
        /// </summary>
        internal static string MSGDeleteROIConfig {
            get {
                return ResourceManager.GetString("MSGDeleteROIConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove ROI definition &quot;{0}&quot;?.
        /// </summary>
        internal static string MSGDeleteROIDefinition {
            get {
                return ResourceManager.GetString("MSGDeleteROIDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove ROI primitive?.
        /// </summary>
        internal static string MSGDeleteROIPrimitive {
            get {
                return ResourceManager.GetString("MSGDeleteROIPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changing device type causes initialization of input fields. OK?.
        /// </summary>
        internal static string MSGDeviceTypeChanging {
            get {
                return ResourceManager.GetString("MSGDeviceTypeChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spectrum File &quot;{0}&quot; was modified. Save changes?.
        /// </summary>
        internal static string MSGFileOverwriteConfirmation {
            get {
                return ResourceManager.GetString("MSGFileOverwriteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initialize all color settings?.
        /// </summary>
        internal static string MSGInitializeAllColorSetting {
            get {
                return ResourceManager.GetString("MSGInitializeAllColorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spectrum will be initialized due to incompatible parameters and no pulse data..
        /// </summary>
        internal static string MSGInitializingSpectrum {
            get {
                return ResourceManager.GetString("MSGInitializingSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New nuclide definition file has been created..
        /// </summary>
        internal static string MSGNewNuclideDefinitionFileCreated {
            get {
                return ResourceManager.GetString("MSGNewNuclideDefinitionFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pick up calibration point from spectrum chart..
        /// </summary>
        internal static string MSGPickUpCalibrationPoint {
            get {
                return ResourceManager.GetString("MSGPickUpCalibrationPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pick up channel #1 from spectrum chart..
        /// </summary>
        internal static string MSGPickUpChannel1 {
            get {
                return ResourceManager.GetString("MSGPickUpChannel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pick up channel #2 from spectrum chart..
        /// </summary>
        internal static string MSGPickUpChannel2 {
            get {
                return ResourceManager.GetString("MSGPickUpChannel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pick up channel #3 from spectrum chart..
        /// </summary>
        internal static string MSGPickUpChannel3 {
            get {
                return ResourceManager.GetString("MSGPickUpChannel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Modify values and push execution button..
        /// </summary>
        internal static string MSGProceedCalibration {
            get {
                return ResourceManager.GetString("MSGProceedCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save energy calibration parmeters to current device configuration?.
        /// </summary>
        internal static string MSGSaveEnergyCalibration {
            get {
                return ResourceManager.GetString("MSGSaveEnergyCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nuclide definition has been modified. Save?.
        /// </summary>
        internal static string MSGSavingNuclideDefinition {
            get {
                return ResourceManager.GetString("MSGSavingNuclideDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changing thermometer type causes initialization of input fields. OK?.
        /// </summary>
        internal static string MSGThermometerTypeChanging {
            get {
                return ResourceManager.GetString("MSGThermometerTypeChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multipoint Calibration.
        /// </summary>
        internal static string MultipointCalibrationString {
            get {
                return ResourceManager.GetString("MultipointCalibrationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NDBitmap {
            get {
                object obj = ResourceManager.GetObject("NDBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Device Configuration.
        /// </summary>
        internal static string NewDeviceConfigPrefix {
            get {
                return ResourceManager.GetString("NewDeviceConfigPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New File.
        /// </summary>
        internal static string NewFilePrefix {
            get {
                return ResourceManager.GetString("NewFilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New ROI Configuration.
        /// </summary>
        internal static string NewROIConfigPrefix {
            get {
                return ResourceManager.GetString("NewROIConfigPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NOBG {
            get {
                object obj = ResourceManager.GetObject("NOBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap None {
            get {
                object obj = ResourceManager.GetObject("None", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nopeak {
            get {
                object obj = ResourceManager.GetObject("nopeak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoSmooth {
            get {
                object obj = ResourceManager.GetObject("NoSmooth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message.
        /// </summary>
        internal static string NotificationDialogTitle {
            get {
                return ResourceManager.GetString("NotificationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Spectrum File.
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap peak {
            get {
                object obj = ResourceManager.GetObject("peak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на %.
        /// </summary>
        internal static string PercentCharacter {
            get {
                return ResourceManager.GetString("PercentCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plus {
            get {
                object obj = ResourceManager.GetObject("Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  ({0}%).
        /// </summary>
        internal static string ProgressString {
            get {
                return ResourceManager.GetString("ProgressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restart application to apply settings..
        /// </summary>
        internal static string RestartRequiredMessage {
            get {
                return ResourceManager.GetString("RestartRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Addition.
        /// </summary>
        internal static string ROIPrimitiveOperationTypeAddition {
            get {
                return ResourceManager.GetString("ROIPrimitiveOperationTypeAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subtraction.
        /// </summary>
        internal static string ROIPrimitiveOperationTypeSubtraction {
            get {
                return ResourceManager.GetString("ROIPrimitiveOperationTypeSubtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BG Difference.
        /// </summary>
        internal static string ROIPrimitiveTypeBGDifference {
            get {
                return ResourceManager.GetString("ROIPrimitiveTypeBGDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Covell Method.
        /// </summary>
        internal static string ROIPrimitiveTypeCovellMethod {
            get {
                return ResourceManager.GetString("ROIPrimitiveTypeCovellMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ROI Reference.
        /// </summary>
        internal static string ROIPrimitiveTypeROIReference {
            get {
                return ResourceManager.GetString("ROIPrimitiveTypeROIReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Spectrum File As.
        /// </summary>
        internal static string SaveFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SMA {
            get {
                object obj = ResourceManager.GetObject("SMA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spectrum Files (*.xml)|*.xml|All Files (*.*)|*.*.
        /// </summary>
        internal static string SpectrumFileFilter {
            get {
                return ResourceManager.GetString("SpectrumFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        internal static string ThermometerTypeNone {
            get {
                return ResourceManager.GetString("ThermometerTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (unknown).
        /// </summary>
        internal static string UnknownNuclide {
            get {
                return ResourceManager.GetString("UnknownNuclide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (unnamed).
        /// </summary>
        internal static string UnnamedSpectrumName {
            get {
                return ResourceManager.GetString("UnnamedSpectrumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на version {0}.
        /// </summary>
        internal static string VersionString {
            get {
                return ResourceManager.GetString("VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WMA {
            get {
                object obj = ResourceManager.GetObject("WMA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zoomin {
            get {
                object obj = ResourceManager.GetObject("Zoomin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ZoominSelection {
            get {
                object obj = ResourceManager.GetObject("ZoominSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zoomout {
            get {
                object obj = ResourceManager.GetObject("Zoomout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ベクモニロゴ {
            get {
                object obj = ResourceManager.GetObject("ベクモニロゴ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
