//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BecquerelMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BecquerelMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2σ.
        /// </summary>
        internal static string _2Sigma {
            get {
                return ResourceManager.GetString("2Sigma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BecqMoni ATOM Edition.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Atom Spectra v3 file.
        /// </summary>
        internal static string AtomSpectraExportDialogTitle {
            get {
                return ResourceManager.GetString("AtomSpectraExportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atom Spectra Files (*.txt)|*.txt|All Files (*.*)|*.*.
        /// </summary>
        internal static string AtomSpectraFileFilter {
            get {
                return ResourceManager.GetString("AtomSpectraFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap attach {
            get {
                object obj = ResourceManager.GetObject("attach", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        internal static string Attach_BTN {
            get {
                return ResourceManager.GetString("Attach.BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose background spectrum file.
        /// </summary>
        internal static string BackgroundSelectionDialogTitle {
            get {
                return ResourceManager.GetString("BackgroundSelectionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bar {
            get {
                object obj = ResourceManager.GetObject("bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon becqmoni {
            get {
                object obj = ResourceManager.GetObject("becqmoni", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BecqMoniLogo {
            get {
                object obj = ResourceManager.GetObject("BecqMoniLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Beta program expires at {0}).
        /// </summary>
        internal static string BetaProgramExpirationDateString {
            get {
                return ResourceManager.GetString("BetaProgramExpirationDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BG {
            get {
                object obj = ResourceManager.GetObject("BG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bgfit {
            get {
                object obj = ResourceManager.GetObject("bgfit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bq/g.
        /// </summary>
        internal static string Bkg {
            get {
                return ResourceManager.GetString("Bkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string ButtonRefresh {
            get {
                return ResourceManager.GetString("ButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calibration function should be monotonically increasing at channel &gt; 0. Re-check Calibration points!.
        /// </summary>
        internal static string CalibrationFunctionError {
            get {
                return ResourceManager.GetString("CalibrationFunctionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap channel {
            get {
                object obj = ResourceManager.GetObject("channel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ch.
        /// </summary>
        internal static string ChartChannelShort {
            get {
                return ResourceManager.GetString("ChartChannelShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Counts:.
        /// </summary>
        internal static string ChartHeaderBGCounts {
            get {
                return ResourceManager.GetString("ChartHeaderBGCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel:.
        /// </summary>
        internal static string ChartHeaderChannel {
            get {
                return ResourceManager.GetString("ChartHeaderChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BG Ratio:.
        /// </summary>
        internal static string ChartHeaderCountBGRatio {
            get {
                return ResourceManager.GetString("ChartHeaderCountBGRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy[keV]:.
        /// </summary>
        internal static string ChartHeaderEnergy {
            get {
                return ResourceManager.GetString("ChartHeaderEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FWHM:.
        /// </summary>
        internal static string ChartHeaderFWHM {
            get {
                return ResourceManager.GetString("ChartHeaderFWHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Counts:.
        /// </summary>
        internal static string ChartHeaderGrossCounts {
            get {
                return ResourceManager.GetString("ChartHeaderGrossCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Counts:.
        /// </summary>
        internal static string ChartHeaderNetCounts {
            get {
                return ResourceManager.GetString("ChartHeaderNetCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net CPS:.
        /// </summary>
        internal static string ChartHeaderNetCps {
            get {
                return ResourceManager.GetString("ChartHeaderNetCps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak counts:.
        /// </summary>
        internal static string ChartHeaderPeakCounts {
            get {
                return ResourceManager.GetString("ChartHeaderPeakCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Region.
        /// </summary>
        internal static string ChartHeaderSelection {
            get {
                return ResourceManager.GetString("ChartHeaderSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cnt {
            get {
                object obj = ResourceManager.GetObject("cnt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other color....
        /// </summary>
        internal static string ColorBTN {
            get {
                return ResourceManager.GetString("ColorBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open spectrum first, then select Combine menu to another spectrum file..
        /// </summary>
        internal static string CombineEmptySpectrum {
            get {
                return ResourceManager.GetString("CombineEmptySpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different number of channels in combined spectrums! Select proper spectrum file..
        /// </summary>
        internal static string CombineIncorrectChannels {
            get {
                return ResourceManager.GetString("CombineIncorrectChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string ConfirmationDialogTitle {
            get {
                return ResourceManager.GetString("ConfirmationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CONT {
            get {
                object obj = ResourceManager.GetObject("CONT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Copy).
        /// </summary>
        internal static string CopyPostfix {
            get {
                return ResourceManager.GetString("CopyPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cps {
            get {
                object obj = ResourceManager.GetObject("cps", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cps1 {
            get {
                object obj = ResourceManager.GetObject("cps1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cps2 {
            get {
                object obj = ResourceManager.GetObject("cps2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV File.
        /// </summary>
        internal static string CsvExportDialogTitle {
            get {
                return ResourceManager.GetString("CsvExportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Files (*.csv)|*.csv|All Files (*.*)|*.*.
        /// </summary>
        internal static string CsvFileFilter {
            get {
                return ResourceManager.GetString("CsvFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from CSV File.
        /// </summary>
        internal static string CsvImportDialogTitle {
            get {
                return ResourceManager.GetString("CsvImportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete spectrum &quot;{0}&quot;?.
        /// </summary>
        internal static string DeleteSpectrumMessage {
            get {
                return ResourceManager.GetString("DeleteSpectrumMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete unnamed spectrum?.
        /// </summary>
        internal static string DeleteUnnamedSpectrumMessage {
            get {
                return ResourceManager.GetString("DeleteUnnamedSpectrumMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detach.
        /// </summary>
        internal static string Detach_BTN {
            get {
                return ResourceManager.GetString("Detach.BTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AtomSpectraVCP.
        /// </summary>
        internal static string DeviceTypeAtomSpectraVCP {
            get {
                return ResourceManager.GetString("DeviceTypeAtomSpectraVCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Input Device.
        /// </summary>
        internal static string DeviceTypeAudioInput {
            get {
                return ResourceManager.GetString("DeviceTypeAudioInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEMCA USB Adaptor.
        /// </summary>
        internal static string DeviceTypeLEMCA {
            get {
                return ResourceManager.GetString("DeviceTypeLEMCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Down {
            get {
                object obj = ResourceManager.GetObject("Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty device list! You should add new device first!.
        /// </summary>
        internal static string EmptyDeviceList {
            get {
                return ResourceManager.GetString("EmptyDeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ene {
            get {
                object obj = ResourceManager.GetObject("ene", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EnergyCalibration {
            get {
                object obj = ResourceManager.GetObject("EnergyCalibration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EnergyCalibration2 {
            get {
                object obj = ResourceManager.GetObject("EnergyCalibration2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding channel {0}. Error message: {1}.
        /// </summary>
        internal static string ERRAddCalibrationPoints {
            get {
                return ResourceManager.GetString("ERRAddCalibrationPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified file is already open..
        /// </summary>
        internal static string ERRAlreadyOpen {
            get {
                return ResourceManager.GetString("ERRAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified audio device is not found..
        /// </summary>
        internal static string ERRAudioDeviceNotFound {
            get {
                return ResourceManager.GetString("ERRAudioDeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load background spectrum &quot;{0}&quot;..
        /// </summary>
        internal static string ERRBackgroundLoadFailure {
            get {
                return ResourceManager.GetString("ERRBackgroundLoadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect device. Check cable connection and power of the device..
        /// </summary>
        internal static string ERRCannotConnectDevice {
            get {
                return ResourceManager.GetString("ERRCannotConnectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete spectrum. at least one spectrum per file is needed..
        /// </summary>
        internal static string ERRCannotDeleteSpectrum {
            get {
                return ResourceManager.GetString("ERRCannotDeleteSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open WAV file..
        /// </summary>
        internal static string ERRCannotOpenWavFile {
            get {
                return ResourceManager.GetString("ERRCannotOpenWavFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t overwrite any opened file.
        /// </summary>
        internal static string ERRCannotOverwrite {
            get {
                return ResourceManager.GetString("ERRCannotOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retreive device data. (prohibited while measurement processing)
        ///.
        /// </summary>
        internal static string ERRCannotRetreiveDeviceData {
            get {
                return ResourceManager.GetString("ERRCannotRetreiveDeviceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error detected while communicating with device.
        ///.
        /// </summary>
        internal static string ERRDetectedErrorWhileCommunication {
            get {
                return ResourceManager.GetString("ERRDetectedErrorWhileCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device configuration is not selected..
        /// </summary>
        internal static string ERRDeviceConfigNotSelected {
            get {
                return ResourceManager.GetString("ERRDeviceConfigNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missmatched device configuration: to solve this create new file and use Audio Input device..
        /// </summary>
        internal static string ERRDeviceMismatchConfiguration {
            get {
                return ResourceManager.GetString("ERRDeviceMismatchConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate or invalid configuration name..
        /// </summary>
        internal static string ERRDuplicateConfigName {
            get {
                return ResourceManager.GetString("ERRDuplicateConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate GUID for deivce configuration &quot;{0}&quot;.
        /// </summary>
        internal static string ERRDuplicateDeviceConfigGUID {
            get {
                return ResourceManager.GetString("ERRDuplicateDeviceConfigGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate GUID for ROI configuration &quot;{0}&quot;.
        /// </summary>
        internal static string ERRDuplicateROIConfigGUID {
            get {
                return ResourceManager.GetString("ERRDuplicateROIConfigGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device doesn&apos;t contain calibration coefficients. Write them first..
        /// </summary>
        internal static string ERREmptyCoefficients {
            get {
                return ResourceManager.GetString("ERREmptyCoefficients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty port name.
        /// </summary>
        internal static string ERREmptyPortName {
            get {
                return ResourceManager.GetString("ERREmptyPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel may not be installed.
        /// </summary>
        internal static string ERRExcelNotInstalled {
            get {
                return ResourceManager.GetString("ERRExcelNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Expected empty line separator, got: {0}.
        /// </summary>
        internal static string ERRExpectedLineSeparator {
            get {
                return ResourceManager.GetString("ERRExpectedLineSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; couldn&apos;t be opened.
        ///({1}).
        /// </summary>
        internal static string ERRFileOpenFailure {
            get {
                return ResourceManager.GetString("ERRFileOpenFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; couldn&apos;t be saved.
        ///({1}).
        /// </summary>
        internal static string ERRFileSaveFailure {
            get {
                return ResourceManager.GetString("ERRFileSaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware must be updated to the latest version..
        /// </summary>
        internal static string ERRFirmwareMustBeUpdated {
            get {
                return ResourceManager.GetString("ERRFirmwareMustBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel mismatch between device and imported spectra file.
        ///Device channels: {0}, spectrum files channels: {1}.
        /// </summary>
        internal static string ERRImportAtomSpectra {
            get {
                return ResourceManager.GetString("ERRImportAtomSpectra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible channel parameters..
        /// </summary>
        internal static string ERRIncompatibleChannelParameters {
            get {
                return ResourceManager.GetString("ERRIncompatibleChannelParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incrorrect Crc32 checksum! Possible borken coefficients. Try to upload them again..
        /// </summary>
        internal static string ERRIncorrectCRC {
            get {
                return ResourceManager.GetString("ERRIncorrectCRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input device is not set..
        /// </summary>
        internal static string ERRInputDeviceNotSet {
            get {
                return ResourceManager.GetString("ERRInputDeviceNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input an integer..
        /// </summary>
        internal static string ERRInputInteger {
            get {
                return ResourceManager.GetString("ERRInputInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input a number..
        /// </summary>
        internal static string ERRInputNumber {
            get {
                return ResourceManager.GetString("ERRInputNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid channel or energy values.
        /// </summary>
        internal static string ERRInvalidChannelOrEnergyValues {
            get {
                return ResourceManager.GetString("ERRInvalidChannelOrEnergyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device type.
        /// </summary>
        internal static string ERRInvalidDeviceType {
            get {
                return ResourceManager.GetString("ERRInvalidDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input form..
        /// </summary>
        internal static string ERRInvalidInputForm {
            get {
                return ResourceManager.GetString("ERRInvalidInputForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid preset time..
        /// </summary>
        internal static string ERRInvalidPresetTime {
            get {
                return ResourceManager.GetString("ERRInvalidPresetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ROI primitive..
        /// </summary>
        internal static string ERRInvalidROIPrimitive {
            get {
                return ResourceManager.GetString("ERRInvalidROIPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ROI primitive operation..
        /// </summary>
        internal static string ERRInvalidROIPrimitiveOperation {
            get {
                return ResourceManager.GetString("ERRInvalidROIPrimitiveOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load device configuration file(s)..
        /// </summary>
        internal static string ERRLoadingDeviceConfigFailed {
            get {
                return ResourceManager.GetString("ERRLoadingDeviceConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load application configuration file..
        /// </summary>
        internal static string ERRLoadingGlobalConfigFailed {
            get {
                return ResourceManager.GetString("ERRLoadingGlobalConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load nuclide definition file..
        /// </summary>
        internal static string ERRLoadingNuclideDefinitionFile {
            get {
                return ResourceManager.GetString("ERRLoadingNuclideDefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load ROI configuration file(s)..
        /// </summary>
        internal static string ERRLoadingROIConfigFailed {
            get {
                return ResourceManager.GetString("ERRLoadingROIConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified WAV format is not supported by the audio device..
        /// </summary>
        internal static string ERRNotSupportedWavFormat {
            get {
                return ResourceManager.GetString("ERRNotSupportedWavFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Can not open this file. Expected format 3, got: {0}.
        /// </summary>
        internal static string ERROpenAtomSpectraFormat {
            get {
                return ResourceManager.GetString("ERROpenAtomSpectraFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string ErrorExclamation {
            get {
                return ResourceManager.GetString("ErrorExclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read device data from Port: {0}.
        /// </summary>
        internal static string ERRReadDataFromPort {
            get {
                return ResourceManager.GetString("ERRReadDataFromPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read device data from Port!.
        /// </summary>
        internal static string ERRReadDataFromPort_Empty {
            get {
                return ResourceManager.GetString("ERRReadDataFromPort_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save device configuration file..
        /// </summary>
        internal static string ERRSavingDeviceConfigFailed {
            get {
                return ResourceManager.GetString("ERRSavingDeviceConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save application configuration file..
        /// </summary>
        internal static string ERRSavingGlobalConfigFailed {
            get {
                return ResourceManager.GetString("ERRSavingGlobalConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save nuclide definition file..
        /// </summary>
        internal static string ERRSavingNuclideDefinitionFile {
            get {
                return ResourceManager.GetString("ERRSavingNuclideDefinitionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save ROI configuration file..
        /// </summary>
        internal static string ERRSavingROIConfigFailed {
            get {
                return ResourceManager.GetString("ERRSavingROIConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N42 EnergyBoundaryValues not supported. Using current calibration..
        /// </summary>
        internal static string ERRUnsuportedEnergyBoundaryN42 {
            get {
                return ResourceManager.GetString("ERRUnsuportedEnergyBoundaryN42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported calibration method polynom order {0}. Only 2,3,4,5 points exist..
        /// </summary>
        internal static string ERRUnsupportedCalibrationMethod {
            get {
                return ResourceManager.GetString("ERRUnsupportedCalibrationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported calibration points number. Got polynom order = {0}.
        /// </summary>
        internal static string ERRUnsupportedCalibrationOrder {
            get {
                return ResourceManager.GetString("ERRUnsupportedCalibrationOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application works in standalone mode. If you want to use update re-install it..
        /// </summary>
        internal static string ERRUpdateApp {
            get {
                return ResourceManager.GetString("ERRUpdateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cann&apos;t install the latest version. Error happens.
        ///{0}.
        /// </summary>
        internal static string ERRUpdateExc {
            get {
                return ResourceManager.GetString("ERRUpdateExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Some coefficients uploaded with error! Check connection and reupload it again..
        /// </summary>
        internal static string ERRUploadCoefficeintsToDevice {
            get {
                return ResourceManager.GetString("ERRUploadCoefficeintsToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Selected Spectra To File.
        /// </summary>
        internal static string ExportSpectraToFileDialogTitle {
            get {
                return ResourceManager.GetString("ExportSpectraToFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fit1 {
            get {
                object obj = ResourceManager.GetObject("fit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fit2 {
            get {
                object obj = ResourceManager.GetObject("fit2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to set Peak Detection values:
        ///
        ///FWHM at 0 ch - Should be selected according to your fwhm as close to 0 
        ///keV as possible. Select such a peak with the mouse and enter
        /// a value slightly less, than &quot;FWHM ch&quot; in this setting.
        ///
        ///FWHM peak in ch - Choose peak in the center of the spectrum.
        ///The K-40 peak should be great. Enter the value of center 
        ///position in the channels.
        ///
        ///FW peak width ch - The width of the peak in channels. Select peak from
        /// the &quot;FWHM peak in ch&quot; parameter with the mouse and enter t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FWHMPeakConfigDescription {
            get {
                return ResourceManager.GetString("FWHMPeakConfigDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HD {
            get {
                object obj = ResourceManager.GetObject("HD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HD1 {
            get {
                object obj = ResourceManager.GetObject("HD1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon256 {
            get {
                object obj = ResourceManager.GetObject("icon256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Atom Spectra Spectrum File.
        /// </summary>
        internal static string ImportAtomSpectraFileDialogTitle {
            get {
                return ResourceManager.GetString("ImportAtomSpectraFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import N42 Spectrum File.
        /// </summary>
        internal static string ImportN42FileDialogTitle {
            get {
                return ResourceManager.GetString("ImportN42FileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Old Format (0.93Beta or earlier) Spectrum File.
        /// </summary>
        internal static string ImportOldFormatFileDialogTitle {
            get {
                return ResourceManager.GetString("ImportOldFormatFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Spectra From File.
        /// </summary>
        internal static string ImportSpectraFromFileDialogTitle {
            get {
                return ResourceManager.GetString("ImportSpectraFromFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing...
        ///.
        /// </summary>
        internal static string InitializingMessage {
            get {
                return ResourceManager.GetString("InitializingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input Value.
        /// </summary>
        internal static string InvalidValueDialogTitle {
            get {
                return ResourceManager.GetString("InvalidValueDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keV.
        /// </summary>
        internal static string kev {
            get {
                return ResourceManager.GetString("kev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: {0}.
        /// </summary>
        internal static string LabelVCPSpectraInfo {
            get {
                return ResourceManager.GetString("LabelVCPSpectraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to based on pulse shape discrimination algorithm of PRA for audio input devices
        ///http://www.physics.usyd.edu.au/~marek/pra/index.html
        ///
        ///using DockPanel Suite library
        ///http://sourceforge.net/projects/dockpanelsuite/
        ///
        ///using WinMM.Net library
        ///http://winmm.codeplex.com/
        ///
        ///using XPTable library
        ///http://xptable.sourceforge.net/.
        /// </summary>
        internal static string LibraryLicensesMessage {
            get {
                return ResourceManager.GetString("LibraryLicensesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap line {
            get {
                object obj = ResourceManager.GetObject("line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap linear {
            get {
                object obj = ResourceManager.GetObject("linear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading File ( {0} )....
        /// </summary>
        internal static string LoadingFileMessage {
            get {
                return ResourceManager.GetString("LoadingFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap log {
            get {
                object obj = ResourceManager.GetObject("log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove device configuration &quot;{0}&quot;?.
        /// </summary>
        internal static string MessageRemoveDeviceConfig {
            get {
                return ResourceManager.GetString("MessageRemoveDeviceConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minus {
            get {
                object obj = ResourceManager.GetObject("Minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type command and press Enter. Some commands ARE HAZARDOUS!
        ///You must be completely sure, what you are doing..
        /// </summary>
        internal static string MSGAtomSpectraWarning {
            get {
                return ResourceManager.GetString("MSGAtomSpectraWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy calibration is done..
        /// </summary>
        internal static string MSGCalibrationDone {
            get {
                return ResourceManager.GetString("MSGCalibrationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear spectrum?.
        /// </summary>
        internal static string MSGClearSpectrum {
            get {
                return ResourceManager.GetString("MSGClearSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficients uploaded to Atom Spectra Pro successfully..
        /// </summary>
        internal static string MSGCoefficientsUploadedSuccesfull {
            get {
                return ResourceManager.GetString("MSGCoefficientsUploadedSuccesfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM Port:.
        /// </summary>
        internal static string MSGComPort {
            get {
                return ResourceManager.GetString("MSGComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration has been modified. Save?.
        /// </summary>
        internal static string MSGConfirmSaveConfig {
            get {
                return ResourceManager.GetString("MSGConfirmSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete nuclide definition &quot;{0}&quot;?.
        /// </summary>
        internal static string MSGDeleteNuclideDefinition {
            get {
                return ResourceManager.GetString("MSGDeleteNuclideDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove ROI configuration &quot;{0}&quot;?.
        /// </summary>
        internal static string MSGDeleteROIConfig {
            get {
                return ResourceManager.GetString("MSGDeleteROIConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove ROI definition &quot;{0}&quot;?.
        /// </summary>
        internal static string MSGDeleteROIDefinition {
            get {
                return ResourceManager.GetString("MSGDeleteROIDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove ROI primitive?.
        /// </summary>
        internal static string MSGDeleteROIPrimitive {
            get {
                return ResourceManager.GetString("MSGDeleteROIPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing device type causes initialization of input fields. OK?.
        /// </summary>
        internal static string MSGDeviceTypeChanging {
            get {
                return ResourceManager.GetString("MSGDeviceTypeChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum File &quot;{0}&quot; was modified. Save changes?.
        /// </summary>
        internal static string MSGFileOverwriteConfirmation {
            get {
                return ResourceManager.GetString("MSGFileOverwriteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize all color settings?.
        /// </summary>
        internal static string MSGInitializeAllColorSetting {
            get {
                return ResourceManager.GetString("MSGInitializeAllColorSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum will be ERASED due to incompatible parameters (number of channels and channel pitch) and no pulse data..
        /// </summary>
        internal static string MSGInitializingSpectrum {
            get {
                return ResourceManager.GetString("MSGInitializingSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New nuclide definition file has been created..
        /// </summary>
        internal static string MSGNewNuclideDefinitionFileCreated {
            get {
                return ResourceManager.GetString("MSGNewNuclideDefinitionFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new version avalable. Current version: {0}.
        /// </summary>
        internal static string MSGNoNewVersion {
            get {
                return ResourceManager.GetString("MSGNoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up calibration point from spectrum chart..
        /// </summary>
        internal static string MSGPickUpCalibrationPoint {
            get {
                return ResourceManager.GetString("MSGPickUpCalibrationPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up channel #1 from spectrum chart..
        /// </summary>
        internal static string MSGPickUpChannel1 {
            get {
                return ResourceManager.GetString("MSGPickUpChannel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up channel #2 from spectrum chart..
        /// </summary>
        internal static string MSGPickUpChannel2 {
            get {
                return ResourceManager.GetString("MSGPickUpChannel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up channel #3 from spectrum chart..
        /// </summary>
        internal static string MSGPickUpChannel3 {
            get {
                return ResourceManager.GetString("MSGPickUpChannel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify values and push execution button..
        /// </summary>
        internal static string MSGProceedCalibration {
            get {
                return ResourceManager.GetString("MSGProceedCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update finished. Application WILL RESTART..
        /// </summary>
        internal static string MSGRestartNeeded {
            get {
                return ResourceManager.GetString("MSGRestartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save configuration before writing config to Atom Pro device..
        /// </summary>
        internal static string MSGSaveBeforeWritingData {
            get {
                return ResourceManager.GetString("MSGSaveBeforeWritingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save energy calibration parmeters to current device configuration?.
        /// </summary>
        internal static string MSGSaveEnergyCalibration {
            get {
                return ResourceManager.GetString("MSGSaveEnergyCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuclide definition has been modified. Save?.
        /// </summary>
        internal static string MSGSavingNuclideDefinition {
            get {
                return ResourceManager.GetString("MSGSavingNuclideDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing thermometer type causes initialization of input fields. OK?.
        /// </summary>
        internal static string MSGThermometerTypeChanging {
            get {
                return ResourceManager.GetString("MSGThermometerTypeChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available: {0}.
        ///Before updating save all unsaved data. Application WILL RESTART!
        ///Install update?.
        /// </summary>
        internal static string MSGUpdateLong {
            get {
                return ResourceManager.GetString("MSGUpdateLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update avalable.
        /// </summary>
        internal static string MSGUpdateShort {
            get {
                return ResourceManager.GetString("MSGUpdateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multipoint Calibration.
        /// </summary>
        internal static string MultipointCalibrationString {
            get {
                return ResourceManager.GetString("MultipointCalibrationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export N42 file.
        /// </summary>
        internal static string N42ExportDialogTitle {
            get {
                return ResourceManager.GetString("N42ExportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N42 Files (*.N42)|*.N42|All Files (*.*)|*.*.
        /// </summary>
        internal static string N42FileFilter {
            get {
                return ResourceManager.GetString("N42FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NDBitmap {
            get {
                object obj = ResourceManager.GetObject("NDBitmap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Device Configuration.
        /// </summary>
        internal static string NewDeviceConfigPrefix {
            get {
                return ResourceManager.GetString("NewDeviceConfigPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        internal static string NewFilePrefix {
            get {
                return ResourceManager.GetString("NewFilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ROI Configuration.
        /// </summary>
        internal static string NewROIConfigPrefix {
            get {
                return ResourceManager.GetString("NewROIConfigPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NOBG {
            get {
                object obj = ResourceManager.GetObject("NOBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap None {
            get {
                object obj = ResourceManager.GetObject("None", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nopeak {
            get {
                object obj = ResourceManager.GetObject("nopeak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoSmooth {
            get {
                object obj = ResourceManager.GetObject("NoSmooth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string NotificationDialogTitle {
            get {
                return ResourceManager.GetString("NotificationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to α.
        /// </summary>
        internal static string NucBase_Alpha_Label {
            get {
                return ResourceManager.GetString("NucBase.Alpha.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decay_rads.
        /// </summary>
        internal static string NucBase_API_Data_Method {
            get {
                return ResourceManager.GetString("NucBase.API.Data.Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www-nds.iaea.org/relnsd/v0/data?fields={0}&amp;nuclides={1}&amp;rad_types={2}.
        /// </summary>
        internal static string NucBase_API_IAEA {
            get {
                return ResourceManager.GetString("NucBase.API.IAEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to β-.
        /// </summary>
        internal static string NucBase_BettaMinus_Label {
            get {
                return ResourceManager.GetString("NucBase.BettaMinus.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to β+.
        /// </summary>
        internal static string NucBase_BettaPlus_Label {
            get {
                return ResourceManager.GetString("NucBase.BettaPlus.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all daughters fetched for isotope {0}. Message: {1}.
        /// </summary>
        internal static string NucBase_DaughtersFetchError {
            get {
                return ResourceManager.GetString("NucBase.DaughtersFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch decay radiation. SQL string: {0}. Message: {1}.
        /// </summary>
        internal static string NucBase_DecayRadsFetchError {
            get {
                return ResourceManager.GetString("NucBase.DecayRadsFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EC.
        /// </summary>
        internal static string NucBase_EC {
            get {
                return ResourceManager.GetString("NucBase.EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string NucBase_Gamma {
            get {
                return ResourceManager.GetString("NucBase.Gamma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to γ.
        /// </summary>
        internal static string NucBase_Gamma_Label {
            get {
                return ResourceManager.GetString("NucBase.Gamma.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch Isotope: {0}. {1}.
        /// </summary>
        internal static string NucBase_IsotopeFetchError {
            get {
                return ResourceManager.GetString("NucBase.IsotopeFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: AM-241, AM241, 241AM. Isomer: PA234m1, 234PAm1, PA-234m1.
        /// </summary>
        internal static string NucBase_IsotopeTextBoxTooltip1 {
            get {
                return ResourceManager.GetString("NucBase.IsotopeTextBoxTooltip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        internal static string NucBase_IT {
            get {
                return ResourceManager.GetString("NucBase.IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0.
        /// </summary>
        internal static string NucBase_User_Agent {
            get {
                return ResourceManager.GetString("NucBase.User-Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        internal static string NucBase_X_Ray {
            get {
                return ResourceManager.GetString("NucBase.X-Ray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Spectrum File.
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap peak {
            get {
                object obj = ResourceManager.GetObject("peak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string PercentCharacter {
            get {
                return ResourceManager.GetString("PercentCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plus {
            get {
                object obj = ResourceManager.GetObject("Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0}%).
        /// </summary>
        internal static string ProgressString {
            get {
                return ResourceManager.GetString("ProgressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart application to apply settings..
        /// </summary>
        internal static string RestartRequiredMessage {
            get {
                return ResourceManager.GetString("RestartRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        internal static string ROIPrimitiveOperationTypeAddition {
            get {
                return ResourceManager.GetString("ROIPrimitiveOperationTypeAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtraction.
        /// </summary>
        internal static string ROIPrimitiveOperationTypeSubtraction {
            get {
                return ResourceManager.GetString("ROIPrimitiveOperationTypeSubtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BG Difference.
        /// </summary>
        internal static string ROIPrimitiveTypeBGDifference {
            get {
                return ResourceManager.GetString("ROIPrimitiveTypeBGDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Covell Method.
        /// </summary>
        internal static string ROIPrimitiveTypeCovellMethod {
            get {
                return ResourceManager.GetString("ROIPrimitiveTypeCovellMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROI Reference.
        /// </summary>
        internal static string ROIPrimitiveTypeROIReference {
            get {
                return ResourceManager.GetString("ROIPrimitiveTypeROIReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Spectrum File As.
        /// </summary>
        internal static string SaveFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to σ.
        /// </summary>
        internal static string Sigma {
            get {
                return ResourceManager.GetString("Sigma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SMA {
            get {
                object obj = ResourceManager.GetObject("SMA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum Files (*.xml)|*.xml|All Files (*.*)|*.*.
        /// </summary>
        internal static string SpectrumFileFilter {
            get {
                return ResourceManager.GetString("SpectrumFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SUB {
            get {
                object obj = ResourceManager.GetObject("SUB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ThermometerTypeNone {
            get {
                return ResourceManager.GetString("ThermometerTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unknown).
        /// </summary>
        internal static string UnknownNuclide {
            get {
                return ResourceManager.GetString("UnknownNuclide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unnamed).
        /// </summary>
        internal static string UnnamedSpectrumName {
            get {
                return ResourceManager.GetString("UnnamedSpectrumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Up {
            get {
                object obj = ResourceManager.GetObject("Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string VCPDeviceStatusConnected {
            get {
                return ResourceManager.GetString("VCPDeviceStatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string VCPDeviceStatusUnknown {
            get {
                return ResourceManager.GetString("VCPDeviceStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version {0}.
        /// </summary>
        internal static string VersionString {
            get {
                return ResourceManager.GetString("VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WMA {
            get {
                object obj = ResourceManager.GetObject("WMA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zoomin {
            get {
                object obj = ResourceManager.GetObject("Zoomin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ZoominSelection {
            get {
                object obj = ResourceManager.GetObject("ZoominSelection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Zoomout {
            get {
                object obj = ResourceManager.GetObject("Zoomout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ベクモニロゴ {
            get {
                object obj = ResourceManager.GetObject("ベクモニロゴ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
