using BecquerelMonitor;

namespace AmplitudaUsbTests
{
    public static class ReaderTests
    {
        static string Parse(string id)
        {
            return AmplitudaUsbReader.ParseSerialFromInstanceId(id);
        }

        // The serial number must come from the instance id Windows recorded at plug-in time:
        // the device stops answering string-descriptor requests while it streams at a high rate.
        public static void TestSerialFromUsbInstanceId()
        {
            T.True(Parse(@"USB\VID_534B&PID_0874\02164") == "02164", "serial is the last segment of the USB device id");
            T.True(Parse(@"usb\vid_534b&pid_0874\02164") == "02164", "the id is matched case-insensitively");
            T.True(Parse(@"USB\VID_0000&PID_0002\5&389AB2C2&0&4") == "", "an id generated by Windows means: a USB device without a serial number");
            T.True(Parse(@"USB\VID_0416&PID_A0F8&MI_01\6&1ECC734A&0&0001") == null, "an interface node of a composite device is not the device itself: keep walking up");
            T.True(Parse(@"HID\VID_534B&PID_0874\8&1C98ED0&0&0000") == null, "a HID node is not the USB device: keep walking up");
            T.True(Parse(@"USB\VID_534B&PID_0874") == null, "an id without the instance part is ignored");
            T.True(Parse(null) == null && Parse("") == null, "null and empty ids are ignored");
        }
    }
}
