# -*- coding: utf-8 -*-
# П94: RegionNearestFace обязан видеть ДЫРЫ — области, стоящие в списке раньше (кристалл в отражателе,
# отражатель в корпусе): расстояние до них — евклидово до тела области.
import io
p = 'BecquerelMonitor/EfficiencyMaker/ElectronTransport.cs'
s = io.open(p, 'rb').read().decode('utf-8-sig')
old = ("        /// (`AMBER44`, П94) То же для ЛЮБОЙ области сцены: расстояние от точки\r\n"
       "        /// внутри области до ближайшей её границы, см, — нижняя граница пути до\r\n"
       "        /// выхода из неё по любому направлению. У кольца смотрится и внутренний\r\n"
       "        /// радиус: слой обвязки — кольцо вокруг кристалла, и ближайшая граница\r\n"
       "        /// у него обычно внутренняя. Ранний выход переноса в слое\r\n"
       "        /// (<see cref=\"WalkInLayers\"/>): пробег короче — электрон погибнет в\r\n"
       "        /// этой области при любой траектории, кристалла ему не видать. Без\r\n"
       "        /// этого на 59.5 кэВ каждый фотоэлектрон пробы и оправы шёл десятками\r\n"
       "        /// шагов с разбором луча на каждом (измерено: ×3 к цене истории).\r\n"
       "        /// </summary>\r\n"
       "        static double RegionNearestFace(Region r, double x, double y, double z)\r\n"
       "        {\r\n"
       "            double d = Math.Min(z - r.ZMin, r.ZMax - z);\r\n"
       "            if (r.IsBox)\r\n"
       "            {\r\n"
       "                d = Math.Min(d, Math.Min(r.AX - Math.Abs(x), r.AY - Math.Abs(y)));\r\n"
       "            }\r\n"
       "            else\r\n"
       "            {\r\n"
       "                double rad = Math.Sqrt(x * x + y * y);\r\n"
       "                d = Math.Min(d, r.ROut - rad);\r\n"
       "                if (r.RIn > 0.0)\r\n"
       "                {\r\n"
       "                    d = Math.Min(d, rad - r.RIn);\r\n"
       "                }\r\n"
       "            }\r\n"
       "\r\n"
       "            return d > 0.0 ? d : 0.0;\r\n"
       "        }\r\n")
new = ("        /// (`AMBER44`, П94) То же для ЛЮБОЙ области сцены: расстояние от точки\r\n"
       "        /// внутри области до ближайшей её границы, см, — нижняя граница пути до\r\n"
       "        /// выхода из неё по любому направлению. ⚠ Области сцены ВЛОЖЕНЫ и\r\n"
       "        /// перекрываются, область точки — ПЕРВАЯ по списку из накрывающих\r\n"
       "        /// (<see cref=\"At\"/>): боковой отражатель — брус, накрывающий и\r\n"
       "        /// кристалл, корпус накрывает отражатель. Значит, границы области —\r\n"
       "        /// не только её собственные стенки, но и тела всех областей, стоящих\r\n"
       "        /// в списке РАНЬШЕ (дыры в ней); до дыры берётся евклидово расстояние\r\n"
       "        /// до её тела. У кольца смотрится и внутренний радиус. Ранний выход\r\n"
       "        /// переноса в слое (<see cref=\"WalkInLayers\"/>): пробег короче —\r\n"
       "        /// электрон погибнет в этой области при любой траектории, кристалла\r\n"
       "        /// ему не видать. Без этого на 59.5 кэВ каждый фотоэлектрон пробы и\r\n"
       "        /// оправы шёл десятками шагов с разбором луча на каждом (измерено:\r\n"
       "        /// ×3 к цене истории на RC103, ×5 на ASN16 с пробой Lu₂O₃).\r\n"
       "        /// </summary>\r\n"
       "        double RegionNearestFace(Region r, double x, double y, double z)\r\n"
       "        {\r\n"
       "            double d = Math.Min(z - r.ZMin, r.ZMax - z);\r\n"
       "            double rad = Math.Sqrt(x * x + y * y);\r\n"
       "            if (r.IsBox)\r\n"
       "            {\r\n"
       "                d = Math.Min(d, Math.Min(r.AX - Math.Abs(x), r.AY - Math.Abs(y)));\r\n"
       "            }\r\n"
       "            else\r\n"
       "            {\r\n"
       "                d = Math.Min(d, r.ROut - rad);\r\n"
       "                if (r.RIn > 0.0)\r\n"
       "                {\r\n"
       "                    d = Math.Min(d, rad - r.RIn);\r\n"
       "                }\r\n"
       "            }\r\n"
       "\r\n"
       "            // Дыры: области, стоящие в списке раньше этой.\r\n"
       "            Region[] all = this.regionArray;\r\n"
       "            for (int i = 0; i < all.Length && d > 0.0; i++)\r\n"
       "            {\r\n"
       "                Region h = all[i];\r\n"
       "                if (h == r)\r\n"
       "                {\r\n"
       "                    break;\r\n"
       "                }\r\n"
       "\r\n"
       "                double dz = Math.Max(0.0, Math.Max(h.ZMin - z, z - h.ZMax));\r\n"
       "                double dxy;\r\n"
       "                if (h.IsBox)\r\n"
       "                {\r\n"
       "                    double dx = Math.Max(0.0, Math.Abs(x) - h.AX);\r\n"
       "                    double dy = Math.Max(0.0, Math.Abs(y) - h.AY);\r\n"
       "                    dxy = Math.Sqrt(dx * dx + dy * dy);\r\n"
       "                }\r\n"
       "                else\r\n"
       "                {\r\n"
       "                    dxy = Math.Max(0.0, Math.Max(rad - h.ROut, h.RIn - rad));\r\n"
       "                }\r\n"
       "\r\n"
       "                d = Math.Min(d, Math.Sqrt(dxy * dxy + dz * dz));\r\n"
       "            }\r\n"
       "\r\n"
       "            return d > 0.0 ? d : 0.0;\r\n"
       "        }\r\n")
assert s.count(old) == 1, 'old'
s = s.replace(old, new)
old2 = "                if (residual / density <= RegionNearestFace(here, x, y, z))\r\n"
new2 = "                if (residual / density <= this.RegionNearestFace(here, x, y, z))\r\n"
assert s.count(old2) == 1, 'old2'
s = s.replace(old2, new2)
io.open(p, 'wb').write(b'\xef\xbb\xbf' + s.encode('utf-8'))
print('ok')
