# -*- coding: utf-8 -*-
# П94: вместо сброса кэша луча — СНИМОК и ВОЗВРАТ вокруг переноса электрона в слоях: обход кванта после
# электрона продолжается с ТЕМ ЖЕ кэшем, что без ключа (на голом кристалле eltr1 = off побайтно).
import io
p = 'BecquerelMonitor/EfficiencyMaker/ElectronTransport.cs'
s = io.open(p, 'rb').read().decode('utf-8-sig')
old = ("            // ⛔ КЭШ ЛУЧА — ЗАБЫТЬ (П94 §7.1). `At` доверяет разобранному лучу,\r\n"
       "            // если точка лежит на нём в 10 нм и `along > 1e-7`, — верно, пока\r\n"
       "            // луч разбирал сам обход, идущий по нему. Точка выхода электрона к\r\n"
       "            // лучу кванта не относится, а совпасть с ним в 10 нм на 20 млн\r\n"
       "            // историй успевает: измерено на голом кристалле — 6 бинов по\r\n"
       "            // одному отсчёту, ключ там обязан быть инертен. Разбор заново —\r\n"
       "            // один поиск области на вылет.\r\n"
       "            this.rayValid = false;\r\n"
       "            this.CountLayerEscapes++;\r\n"
       "            double tOut = tExit - this.LayerBremsstrahlung(x, y, z, tExit);\r\n"
       "            double tBack = tOut;\r\n"
       "            if (!this.TransportInLayers(ref x, ref y, ref z, ref ux, ref uy, ref uz, ref tBack, depth))\r\n"
       "            {\r\n"
       "                escaped += tExit;\r\n"
       "                return false;\r\n"
       "            }\r\n"
       "\r\n")
new = ("            // ⛔ КЭШ ЛУЧА — СНИМОК И ВОЗВРАТ (П94 §7.1). `At` доверяет\r\n"
       "            // разобранному лучу, если точка лежит на нём в 10 нм и\r\n"
       "            // `along > 1e-7`, — верно, пока луч разбирал сам обход, идущий по\r\n"
       "            // нему. Точка выхода электрона к лучу кванта не относится, а\r\n"
       "            // совпасть с ним в 10 нм на 20 млн историй успевает (измерено на\r\n"
       "            // голом кристалле: 6 бинов по одному отсчёту, а ключ там обязан\r\n"
       "            // быть инертен); и наоборот — луч электрона, оставшийся в кэше,\r\n"
       "            // сбил бы обход кванта. Потому кэш кванта прячется на время\r\n"
       "            // переноса электрона и возвращается тем же (`SaveRay`/`RestoreRay`):\r\n"
       "            // обход кванта продолжается ровно тем кэшем, что без ключа.\r\n"
       "            this.SaveRay();\r\n"
       "            this.CountLayerEscapes++;\r\n"
       "            double tOut = tExit - this.LayerBremsstrahlung(x, y, z, tExit);\r\n"
       "            double tBack = tOut;\r\n"
       "            bool back = this.TransportInLayers(ref x, ref y, ref z, ref ux, ref uy, ref uz, ref tBack, depth);\r\n"
       "            this.RestoreRay();\r\n"
       "            if (!back)\r\n"
       "            {\r\n"
       "                escaped += tExit;\r\n"
       "                return false;\r\n"
       "            }\r\n"
       "\r\n")
assert s.count(old) == 1, 'old'
s = s.replace(old, new)
old2 = ("        bool TransportInLayers(ref double x, ref double y, ref double z,\r\n"
        "                               ref double ux, ref double uy, ref double uz,\r\n"
        "                               ref double t, int depth)\r\n"
        "        {\r\n"
        "            bool entered = this.WalkInLayers(ref x, ref y, ref z, ref ux, ref uy, ref uz, ref t);\r\n"
        "            // ⛔ КЭШ ЛУЧА разобран ЗДЕСЬ лучами электрона — обходу кванта он\r\n"
        "            // чужой (П94 §7.1): забыть, чтобы следующий `At`/`StepToBoundary`\r\n"
        "            // кванта разобрал свой луч заново, а не поверил чужому на 10 нм.\r\n"
        "            this.rayValid = false;\r\n"
        "            return entered;\r\n"
        "        }\r\n"
        "\r\n"
        '        /// <summary>Тело <see cref="TransportInLayers"/>; кэш луча снимает обёртка.</summary>\r\n'
        "        bool WalkInLayers(ref double x, ref double y, ref double z,\r\n"
        "                          ref double ux, ref double uy, ref double uz, ref double t)\r\n"
        "        {\r\n"
        "            // Точка старта — на луче кванта (занос) или у грани (возврат): кэш\r\n"
        "            // кванта ей не судья — искать область перебором.\r\n"
        "            this.rayValid = false;\r\n"
        "            double fraction = this.ElectronStepFraction;\r\n")
new2 = ("        bool TransportInLayers(ref double x, ref double y, ref double z,\r\n"
        "                               ref double ux, ref double uy, ref double uz,\r\n"
        "                               ref double t, int depth)\r\n"
        "        {\r\n"
        "            // ⚠ Зовущий обязан спрятать кэш луча кванта (`SaveRay`) и вернуть\r\n"
        "            // его после (`RestoreRay`): здесь луч разбирается заново лучами\r\n"
        "            // электрона, и кэш кванта после этого чужой (П94 §7.1).\r\n"
        "            double fraction = this.ElectronStepFraction;\r\n")
assert s.count(old2) == 1, 'old2'
s = s.replace(old2, new2)
io.open(p, 'wb').write(b'\xef\xbb\xbf' + s.encode('utf-8'))

p = 'BecquerelMonitor/EfficiencyMaker/EfficiencySimulator.cs'
s = io.open(p, 'rb').read().decode('utf-8-sig')
old3 = ("            this.ElectronBirthDirection(birth, tIn, rx, ry, rz, out uxIn, out uyIn, out uzIn);\r\n"
        "            if (!this.TransportInLayers(ref xIn, ref yIn, ref zIn, ref uxIn, ref uyIn, ref uzIn, ref tIn, 0))\r\n"
        "            {\r\n"
        "                return false;\r\n"
        "            }\r\n")
new3 = ("            this.ElectronBirthDirection(birth, tIn, rx, ry, rz, out uxIn, out uyIn, out uzIn);\r\n"
        "            // Кэш луча кванта — спрятать на время переноса электрона и вернуть\r\n"
        "            // (П94 §7.1): обход кванта продолжается своим кэшем.\r\n"
        "            this.SaveRay();\r\n"
        "            bool entered = this.TransportInLayers(ref xIn, ref yIn, ref zIn, ref uxIn, ref uyIn, ref uzIn, ref tIn, 0);\r\n"
        "            this.RestoreRay();\r\n"
        "            if (!entered)\r\n"
        "            {\r\n"
        "                return false;\r\n"
        "            }\r\n")
assert s.count(old3) == 1, 'old3'
s = s.replace(old3, new3)
old4 = ("        // рабочие буферы сбора: события «вход/выход» и отрезки одной области\r\n"
        "        double[] eventT;\r\n"
        "        int[] eventCode;\r\n"
        "        readonly double[] spanBuf = new double[4];\r\n")
new4 = old4 + ("\r\n"
        "        // (`AMBER44`, П94 §7.1) СНИМОК КЭША ЛУЧА на время переноса электрона в\r\n"
        "        // слоях обвязки (`TransportInLayers`): тот разбирает луч заново лучами\r\n"
        "        // электрона, а `At` доверяет кэшу по близости точки к лучу в 10 нм — и\r\n"
        "        // обход кванта после электрона получил бы чужой кэш. Массивы не копируются,\r\n"
        "        // а МЕНЯЮТСЯ МЕСТАМИ с запасной парой той же длины; вложенности переноса\r\n"
        "        // нет (снимок один), глубина считается на случай, если появится.\r\n"
        "        double[] raySpareCross, raySaveCross;\r\n"
        "        Region[] raySpareSeg, raySaveSeg;\r\n"
        "        int raySaveCount, raySaveDepth;\r\n"
        "        double raySaveX, raySaveY, raySaveZ, raySaveUx, raySaveUy, raySaveUz;\r\n"
        "        bool raySaveValid, raySaveSwapped;\r\n"
        "\r\n"
        "        /// <summary>(П94 §7.1) Спрятать кэш луча кванта; сборщику подставляется запасная пара массивов.</summary>\r\n"
        "        void SaveRay()\r\n"
        "        {\r\n"
        "            if (this.raySaveDepth++ > 0)\r\n"
        "            {\r\n"
        "                return;                 // вложенный перенос — снимок уже есть\r\n"
        "            }\r\n"
        "\r\n"
        "            this.raySaveValid = this.rayValid;\r\n"
        "            this.raySaveSwapped = false;\r\n"
        "            if (this.rayCross != null)\r\n"
        "            {\r\n"
        "                if (this.raySpareCross == null || this.raySpareCross.Length != this.rayCross.Length)\r\n"
        "                {\r\n"
        "                    this.raySpareCross = new double[this.rayCross.Length];\r\n"
        "                    this.raySpareSeg = new Region[this.raySeg.Length];\r\n"
        "                }\r\n"
        "\r\n"
        "                this.raySaveCross = this.rayCross;\r\n"
        "                this.raySaveSeg = this.raySeg;\r\n"
        "                this.rayCross = this.raySpareCross;\r\n"
        "                this.raySeg = this.raySpareSeg;\r\n"
        "                this.raySaveCount = this.rayCount;\r\n"
        "                this.raySaveX = this.rayX; this.raySaveY = this.rayY; this.raySaveZ = this.rayZ;\r\n"
        "                this.raySaveUx = this.rayUx; this.raySaveUy = this.rayUy; this.raySaveUz = this.rayUz;\r\n"
        "                this.raySaveSwapped = true;\r\n"
        "            }\r\n"
        "\r\n"
        "            this.rayValid = false;\r\n"
        "        }\r\n"
        "\r\n"
        "        /// <summary>(П94 §7.1) Вернуть кэш луча кванта таким, каким он был до <see cref=\"SaveRay\"/>.</summary>\r\n"
        "        void RestoreRay()\r\n"
        "        {\r\n"
        "            if (--this.raySaveDepth > 0)\r\n"
        "            {\r\n"
        "                return;\r\n"
        "            }\r\n"
        "\r\n"
        "            if (this.raySaveSwapped)\r\n"
        "            {\r\n"
        "                this.raySpareCross = this.rayCross;\r\n"
        "                this.raySpareSeg = this.raySeg;\r\n"
        "                this.rayCross = this.raySaveCross;\r\n"
        "                this.raySeg = this.raySaveSeg;\r\n"
        "                this.rayCount = this.raySaveCount;\r\n"
        "                this.rayX = this.raySaveX; this.rayY = this.raySaveY; this.rayZ = this.raySaveZ;\r\n"
        "                this.rayUx = this.raySaveUx; this.rayUy = this.raySaveUy; this.rayUz = this.raySaveUz;\r\n"
        "                this.raySaveSwapped = false;\r\n"
        "            }\r\n"
        "\r\n"
        "            this.rayValid = this.raySaveValid;\r\n"
        "        }\r\n")
assert s.count(old4) == 1, 'old4'
s = s.replace(old4, new4)
io.open(p, 'wb').write(b'\xef\xbb\xbf' + s.encode('utf-8'))
print('ok')
