//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BecquerelMonitor.WinMM.Properties
{
    using System;


    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BecquerelMonitor.WinMM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;devices&gt;
        ///&lt;manufacturer id=&quot;1&quot; name=&quot;Microsoft Corporation&quot;&gt;&lt;/manufacturer&gt;
        ///&lt;manufacturer id=&quot;2&quot; name=&quot;Creative Labs, Inc&quot;&gt;&lt;/manufacturer&gt;
        ///&lt;manufacturer id=&quot;3&quot; name=&quot;Media Vision, Inc.&quot;&gt;&lt;/manufacturer&gt;
        ///&lt;manufacturer id=&quot;4&quot; name=&quot;Fujitsu Corp.&quot;&gt;&lt;/manufacturer&gt;
        ///&lt;manufacturer id=&quot;20&quot; name=&quot;Artisoft, Inc.&quot;&gt;&lt;/manufacturer&gt;
        ///&lt;manufacturer id=&quot;21&quot; name=&quot;Turtle Beach, Inc.&quot;&gt;&lt;/manufacturer&gt;
        ///&lt;manufacturer id=&quot;22&quot; name=&quot;IBM Corporation&quot;&gt;&lt;/manufacturer&gt;
        ///&lt;manufacturer id=&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Devices
        {
            get
            {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
    }
}
