using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows.Forms;
using System.Xml;

namespace BecquerelMonitor.RoiWizard
{
    // Справка — тот же текст, что в модальном окне страницы. Он не переписан в код,
    // а вынут из index.html скриптом tools/export_help.py в ресурс help.xml: два
    // текста иначе разъедутся после первой же правки страницы. Здесь разбирается
    // то же подмножество разметки, что использует страница: p, b, code, a, таблица.
    public class HelpForm : Form
    {
        const string ResourceName = "BecquerelMonitor.RoiWizard.help.xml";

        readonly RichTextBox view = new RichTextBox();
        readonly List<LinkSpan> links = new List<LinkSpan>();
        readonly bool russian =
            Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName == "ru";

        Font baseFont;
        Font boldFont;
        Font codeFont;

        public HelpForm()
        {
            this.baseFont = WizardTheme.BaseFont;
            this.boldFont = new Font(this.baseFont, FontStyle.Bold);
            this.codeFont = new Font("Consolas", this.baseFont.SizeInPoints, FontStyle.Regular);

            this.Text = RoiWizardStrings.helpTitle;
            this.ClientSize = new Size(940, 660);
            this.MinimumSize = new Size(600, 400);
            this.StartPosition = FormStartPosition.CenterParent;
            this.MinimizeBox = false;
            this.MaximizeBox = true;
            this.ShowInTaskbar = false;

            this.view.Dock = DockStyle.Fill;
            this.view.ReadOnly = true;
            this.view.BorderStyle = BorderStyle.None;
            this.view.BackColor = WizardTheme.Card;
            this.view.ForeColor = WizardTheme.Ink;
            this.view.Font = this.baseFont;
            this.view.DetectUrls = false;          // ссылки расставляет разбор, а не эвристика
            this.view.WordWrap = true;
            this.view.ScrollBars = RichTextBoxScrollBars.Vertical;
            this.view.MouseClick += this.OnViewClick;
            this.view.MouseMove += this.OnViewMove;
            // поля страницы: RichTextBox сам отступов не держит, текст лип бы к рамке
            Panel page = new Panel();
            page.Dock = DockStyle.Fill;
            page.Padding = new Padding(16, 14, 12, 14);
            page.BackColor = WizardTheme.Card;
            page.Controls.Add(this.view);
            this.Controls.Add(page);

            this.Render(LoadHelp(this.russian ? "ru" : "en"));
            this.view.Select(0, 0);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.baseFont.Dispose();
                this.boldFont.Dispose();
                this.codeFont.Dispose();
            }
            base.Dispose(disposing);
        }

        protected override bool ProcessCmdKey(ref Message message, Keys key)
        {
            if (key == Keys.Escape)
            {
                this.Close();
                return true;
            }
            return base.ProcessCmdKey(ref message, key);
        }

        static string LoadHelp(string language)
        {
            Assembly assembly = Assembly.GetExecutingAssembly();
            using (Stream stream = assembly.GetManifestResourceStream(ResourceName))
            {
                if (stream == null)
                {
                    throw new FileNotFoundException(
                        "Resource " + ResourceName + " not found: add RoiWizard\\help.xml " +
                        "to the project as an EmbeddedResource (generated by tools/export_help.py).");
                }
                XmlDocument document = new XmlDocument();
                document.Load(stream);
                XmlNode node = document.SelectSingleNode("/Help/Text[@lang='" + language + "']")
                               ?? document.SelectSingleNode("/Help/Text");
                return node == null ? "" : node.InnerText;
            }
        }

        // ─── разбор разметки ────────────────────────────────────────────────

        sealed class LinkSpan
        {
            public readonly int Start;
            public readonly int Length;
            public readonly string Url;

            public LinkSpan(int start, int length, string url)
            {
                this.Start = start;
                this.Length = length;
                this.Url = url;
            }

            public bool Contains(int index)
            {
                return index >= this.Start && index < this.Start + this.Length;
            }
        }

        int bold;
        int code;
        string linkUrl;
        int linkStart;
        int cellIndex;
        bool headerRow;

        void Render(string html)
        {
            this.view.Clear();
            this.links.Clear();
            foreach (Match token in Regex.Matches(html, @"<[^>]+>|[^<]+"))
            {
                string piece = token.Value;
                if (piece[0] == '<')
                {
                    this.Tag(piece);
                }
                else
                {
                    this.Write(Decode(piece));
                }
            }
        }

        void Tag(string tag)
        {
            bool closing = tag.StartsWith("</", StringComparison.Ordinal);
            Match name = Regex.Match(tag, @"^</?\s*([a-zA-Z]+)");
            switch (name.Groups[1].Value.ToLowerInvariant())
            {
                case "p":
                    if (!closing)
                    {
                        this.Break(2);
                    }
                    return;
                case "b":
                    this.bold += closing ? -1 : 1;
                    return;
                case "code":
                    this.code += closing ? -1 : 1;
                    return;
                case "a":
                    if (closing)
                    {
                        if (this.linkUrl != null)
                        {
                            this.links.Add(new LinkSpan(this.linkStart,
                                this.view.TextLength - this.linkStart, this.linkUrl));
                            this.linkUrl = null;
                        }
                    }
                    else
                    {
                        Match href = Regex.Match(tag, "href=\"([^\"]*)\"");
                        this.linkUrl = href.Success ? Decode(href.Groups[1].Value) : null;
                        this.linkStart = this.view.TextLength;
                    }
                    return;
                case "br":
                    this.Break(1);
                    return;
                case "table":
                    if (!closing)
                    {
                        this.Break(2);
                    }
                    return;
                case "tr":
                    if (!closing)
                    {
                        this.cellIndex = 0;
                        this.Break(this.headerRow ? 1 : 2);
                    }
                    return;
                case "th":
                case "td":
                    // Таблица источников идёт парами: слева «что взято», справа «откуда».
                    // Колонок в RichTextBox нет, поэтому второй столбец уходит строкой
                    // ниже с отступом — при длинных описаниях так читается лучше сетки.
                    this.headerRow = name.Groups[1].Value.ToLowerInvariant() == "th";
                    if (!closing)
                    {
                        if (this.headerRow)
                        {
                            // шапка таблицы одной строкой: «Что взято → Откуда»
                            this.Write(this.cellIndex == 0 ? "" : RoiWizardStrings.helpSourcesArrow);
                        }
                        else if (this.cellIndex == 0)
                        {
                            this.Write("• ");
                        }
                        else
                        {
                            this.Break(1);
                            this.Write("      ");
                        }
                        this.cellIndex++;
                    }
                    return;
                default:
                    return;
            }
        }

        void Break(int lines)
        {
            if (this.view.TextLength == 0)
            {
                return;
            }
            this.Write(lines >= 2 ? "\n\n" : "\n");
        }

        void Write(string text)
        {
            if (text.Length == 0)
            {
                return;
            }
            this.view.SelectionStart = this.view.TextLength;
            this.view.SelectionLength = 0;
            this.view.SelectionFont = this.code > 0 ? this.codeFont
                : (this.bold > 0 || this.headerRow ? this.boldFont : this.baseFont);
            this.view.SelectionColor = this.linkUrl != null ? WizardTheme.Accent : WizardTheme.Ink;
            this.view.AppendText(text);
        }

        static readonly string[][] Entities = {
            new string[] { "&laquo;", "«" }, new string[] { "&raquo;", "»" },
            new string[] { "&alpha;", "α" }, new string[] { "&beta;", "β" },
            new string[] { "&ge;", "≥" }, new string[] { "&le;", "≤" },
            new string[] { "&nbsp;", " " }, new string[] { "&quot;", "\"" },
            new string[] { "&lt;", "<" }, new string[] { "&gt;", ">" },
            new string[] { "&amp;", "&" }
        };

        static string Decode(string text)
        {
            if (text.IndexOf('&') < 0)
            {
                return text;
            }
            StringBuilder result = new StringBuilder(text);
            foreach (string[] pair in Entities)
            {
                result.Replace(pair[0], pair[1]);   // &amp; последним: иначе развернёт остальные дважды
            }
            return result.ToString();
        }

        // ─── ссылки ─────────────────────────────────────────────────────────

        LinkSpan LinkAt(Point point)
        {
            int index = this.view.GetCharIndexFromPosition(point);
            foreach (LinkSpan link in this.links)
            {
                if (link.Contains(index))
                {
                    return link;
                }
            }
            return null;
        }

        void OnViewClick(object sender, MouseEventArgs e)
        {
            LinkSpan link = this.LinkAt(e.Location);
            if (link != null && !string.IsNullOrEmpty(link.Url))
            {
                try
                {
                    Process.Start(link.Url);
                }
                catch (Exception error)
                {
                    MessageBox.Show(this, error.Message, this.Text,
                        MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }
            }
        }

        void OnViewMove(object sender, MouseEventArgs e)
        {
            this.view.Cursor = this.LinkAt(e.Location) != null ? Cursors.Hand : Cursors.Default;
        }
    }
}
